### ISSUE TITLE
An error was encountered compiling the installation service

### ISSUE THREAD

**Issue by NEKGod** [OpenPrinting/cups-commands#3]
======== all in commands ========
make[1]: Entering directory '/root/cups-commands-master/commands'
make[1]: *** No rule to make target 'localize.h', needed by 'cancel.o'.  Stop.
make[1]: Leaving directory '/root/cups-commands-master/commands'
make: *** [Makefile:25: all] Error 1

**Comment by michaelrsweet** [comment]
FWIW, this project will be merged with cups-local soon. But I'll make sure things at least compile (even if they aren't functional yet...)
